STAGE_ORDER = ['Applying Period', 'Screening', 'Interview', 'Test']

POSITIONS = [
    {
        'id': 'pos-001',
        'name': 'Research and Development Officer',
        'requirements': ['3+ years in applied research', 'Strong communication', 'Data analysis proficiency'],
        'niceToHave': ['Technical writing', 'Mentoring experience'],
        'deadline': '2026-06-12',
        'aboutWork': 'Drive product research from idea validation to implementation handoff.',
        'locationType': 'On-site',
    },
    {
        'id': 'pos-002',
        'name': 'Frontend Engineer',
        'requirements': ['React expertise', 'Performance optimization', 'Design collaboration'],
        'niceToHave': ['Accessibility experience', 'Testing with Vitest'],
        'deadline': '2026-07-01',
        'aboutWork': 'Build responsive candidate and recruiter journeys for the HR platform.',
        'locationType': 'Hybrid',
    },
    {
        'id': 'pos-003',
        'name': 'Product Manager',
        'requirements': ['Roadmapping', 'Stakeholder alignment', 'Data-driven decisions'],
        'niceToHave': ['B2B SaaS domain knowledge'],
        'deadline': '2026-06-25',
        'aboutWork': 'Lead roadmap and collaboration across hiring and workflow products.',
        'locationType': 'Remote',
    },
]

CANDIDATES = [
    {
        'id': 'cand-001',
        'name': 'Marlon Reynolds',
        'role': 'Research and Development Officer',
        'appliedPosition': 'Research and Development Officer',
        'stage': 'Applying Period',
        'applicationDate': '2023-10-29',
        'overallScore': 3.5,
        'referred': True,
        'assessmentAdded': False,
        'email': 'marlon.reynolds@example.com',
        'phone': '+94 77 210 1188',
        'location': 'Colombo, Sri Lanka',
        'notes': 'Strong research exposure and a clear interest in process improvement.',
    },
    {
        'id': 'cand-001f',
        'name': 'Alicia Romano',
        'role': 'Frontend Engineer',
        'appliedPosition': 'Frontend Engineer',
        'stage': 'Applying Period',
        'applicationDate': '2024-01-15',
        'overallScore': 4.2,
        'referred': False,
        'assessmentAdded': False,
        'email': 'alicia.romano@example.com',
        'phone': '+94 77 410 2255',
        'location': 'Colombo, Sri Lanka',
        'notes': 'Strong component architecture experience and crisp UI delivery habits.',
    },
    {
        'id': 'cand-001p',
        'name': 'Priya Shah',
        'role': 'Product Manager',
        'appliedPosition': 'Product Manager',
        'stage': 'Applying Period',
        'applicationDate': '2024-01-18',
        'overallScore': 4.4,
        'referred': True,
        'assessmentAdded': False,
        'email': 'priya.shah@example.com',
        'phone': '+94 77 640 2088',
        'location': 'Colombo, Sri Lanka',
        'notes': 'Great product thinking with a practical approach to roadmap tradeoffs.',
    },
    {
        'id': 'cand-002',
        'name': 'Regina Hane',
        'role': 'Research and Development Officer',
        'appliedPosition': 'Research and Development Officer',
        'stage': 'Screening',
        'applicationDate': '2023-10-29',
        'overallScore': 2,
        'referred': False,
        'assessmentAdded': False,
        'email': 'regina.hane@example.com',
        'phone': '+94 71 110 4412',
        'location': 'Gampaha, Sri Lanka',
        'notes': 'Needs stronger case study examples, but the fundamentals are solid.',
    },
    {
        'id': 'cand-002f',
        'name': 'Noah Fern',
        'role': 'Frontend Engineer',
        'appliedPosition': 'Frontend Engineer',
        'stage': 'Screening',
        'applicationDate': '2024-01-11',
        'overallScore': 3.8,
        'referred': True,
        'assessmentAdded': True,
        'email': 'noah.fern@example.com',
        'phone': '+94 70 524 6119',
        'location': 'Galle, Sri Lanka',
        'notes': 'Responsive UI work and CSS system experience stand out clearly.',
    },
    {
        'id': 'cand-002p',
        'name': 'Ethan Cole',
        'role': 'Product Manager',
        'appliedPosition': 'Product Manager',
        'stage': 'Screening',
        'applicationDate': '2024-01-09',
        'overallScore': 3.9,
        'referred': False,
        'assessmentAdded': True,
        'email': 'ethan.cole@example.com',
        'phone': '+94 70 808 9123',
        'location': 'Maharagama, Sri Lanka',
        'notes': 'Solid stakeholder management experience and clear planning habits.',
    },
    {
        'id': 'cand-003',
        'name': 'Curtis Baumbach',
        'role': 'Research and Development Officer',
        'appliedPosition': 'Research and Development Officer',
        'stage': 'Interview',
        'applicationDate': '2023-10-29',
        'overallScore': 3,
        'referred': True,
        'assessmentAdded': False,
        'email': 'curtis.baumbach@example.com',
        'phone': '+94 70 314 6088',
        'location': 'Kandy, Sri Lanka',
        'notes': 'Good communication and reliable background in analytical work.',
    },
    {
        'id': 'cand-003f',
        'name': 'Leah Winters',
        'role': 'Frontend Engineer',
        'appliedPosition': 'Frontend Engineer',
        'stage': 'Interview',
        'applicationDate': '2023-12-29',
        'overallScore': 4.6,
        'referred': False,
        'assessmentAdded': True,
        'email': 'leah.winters@example.com',
        'phone': '+94 76 301 8840',
        'location': 'Kandy, Sri Lanka',
        'notes': 'Excellent design collaboration and accessibility awareness.',
    },
    {
        'id': 'cand-003p',
        'name': 'Maya Roberts',
        'role': 'Product Manager',
        'appliedPosition': 'Product Manager',
        'stage': 'Interview',
        'applicationDate': '2023-12-30',
        'overallScore': 4.7,
        'referred': False,
        'assessmentAdded': True,
        'email': 'maya.roberts@example.com',
        'phone': '+94 75 221 5070',
        'location': 'Kotte, Sri Lanka',
        'notes': 'Strong analytical tradeoff discussions and user-first thinking.',
    },
    {
        'id': 'cand-004',
        'name': 'Jaime Anderson',
        'role': 'Research and Development Officer',
        'appliedPosition': 'Research and Development Officer',
        'stage': 'Applying Period',
        'applicationDate': '2023-10-29',
        'overallScore': 0,
        'referred': False,
        'assessmentAdded': True,
        'email': 'jaime.anderson@example.com',
        'phone': '+94 76 623 3311',
        'location': 'Negombo, Sri Lanka',
        'notes': 'Assessment pending review by the hiring manager.',
    },
    {
        'id': 'cand-004f',
        'name': 'Owen Mercer',
        'role': 'Frontend Engineer',
        'appliedPosition': 'Frontend Engineer',
        'stage': 'Test',
        'applicationDate': '2023-12-21',
        'overallScore': 4.0,
        'referred': False,
        'assessmentAdded': True,
        'email': 'owen.mercer@example.com',
        'phone': '+94 72 198 7604',
        'location': 'Negombo, Sri Lanka',
        'notes': 'Delivered a polished test implementation with strong attention to detail.',
    },
    {
        'id': 'cand-004p',
        'name': 'Daniel Fox',
        'role': 'Product Manager',
        'appliedPosition': 'Product Manager',
        'stage': 'Test',
        'applicationDate': '2023-12-14',
        'overallScore': 4.1,
        'referred': True,
        'assessmentAdded': True,
        'email': 'daniel.fox@example.com',
        'phone': '+94 71 441 3199',
        'location': 'Moratuwa, Sri Lanka',
        'notes': 'Great project framing and reliable roadmap communication.',
    },
    {
        'id': 'cand-005',
        'name': 'Kristi Sipes',
        'role': 'Research and Development Officer',
        'appliedPosition': 'Research and Development Officer',
        'stage': 'Screening',
        'applicationDate': '2023-10-20',
        'overallScore': 3.5,
        'referred': False,
        'assessmentAdded': True,
        'email': 'kristi.sipes@example.com',
        'phone': '+94 72 702 3391',
        'location': 'Colombo, Sri Lanka',
        'notes': 'Screened successfully. Ready for a deeper interview discussion.',
    },
    {
        'id': 'cand-006',
        'name': 'Randy Dibbert',
        'role': 'Research and Development Officer',
        'appliedPosition': 'Research and Development Officer',
        'stage': 'Screening',
        'applicationDate': '2023-10-18',
        'overallScore': 3.5,
        'referred': False,
        'assessmentAdded': True,
        'email': 'randy.dibbert@example.com',
        'phone': '+94 77 324 9084',
        'location': 'Matara, Sri Lanka',
        'notes': 'Balanced profile with good technical clarity and calm communication.',
    },
    {
        'id': 'cand-007',
        'name': 'Jane Anderson',
        'role': 'Research and Development Officer',
        'appliedPosition': 'Research and Development Officer',
        'stage': 'Screening',
        'applicationDate': '2023-10-18',
        'overallScore': 0,
        'referred': False,
        'assessmentAdded': False,
        'email': 'jane.anderson@example.com',
        'phone': '+94 77 888 9010',
        'location': 'Kotte, Sri Lanka',
        'notes': 'Waiting for final screening notes before advancing.',
    },
    {
        'id': 'cand-008',
        'name': 'Shelia Doyle',
        'role': 'Research and Development Officer',
        'appliedPosition': 'Research and Development Officer',
        'stage': 'Screening',
        'applicationDate': '2023-10-13',
        'overallScore': 4.5,
        'referred': True,
        'assessmentAdded': True,
        'email': 'shelia.doyle@example.com',
        'phone': '+94 75 901 2234',
        'location': 'Galle, Sri Lanka',
        'notes': 'Strong review. Good candidate to move into interview.',
    },
    {
        'id': 'cand-009',
        'name': 'Cassandra Hartmann',
        'role': 'Research and Development Officer',
        'appliedPosition': 'Research and Development Officer',
        'stage': 'Screening',
        'applicationDate': '2023-10-11',
        'overallScore': 4,
        'referred': False,
        'assessmentAdded': True,
        'email': 'cassandra.hartmann@example.com',
        'phone': '+94 71 593 8844',
        'location': 'Kurunegala, Sri Lanka',
        'notes': 'Very organized candidate with clear domain thinking.',
    },
    {
        'id': 'cand-010',
        'name': 'Cameron Dickens',
        'role': 'Research and Development Officer',
        'appliedPosition': 'Research and Development Officer',
        'stage': 'Interview',
        'applicationDate': '2023-09-03',
        'overallScore': 4,
        'referred': False,
        'assessmentAdded': True,
        'email': 'cameron.dickens@example.com',
        'phone': '+94 77 112 4455',
        'location': 'Colombo, Sri Lanka',
        'notes': 'Interview questions were answered clearly with strong ownership.',
    },
    {
        'id': 'cand-011',
        'name': 'Merle Vandervort',
        'role': 'Research and Development Officer',
        'appliedPosition': 'Research and Development Officer',
        'stage': 'Interview',
        'applicationDate': '2023-09-09',
        'overallScore': 4,
        'referred': False,
        'assessmentAdded': True,
        'email': 'merle.vandervort@example.com',
        'phone': '+94 76 501 6721',
        'location': 'Nugegoda, Sri Lanka',
        'notes': 'Technically strong and comfortable with structured problem solving.',
    },
    {
        'id': 'cand-012',
        'name': 'Jasmine Wiza',
        'role': 'Research and Development Officer',
        'appliedPosition': 'Research and Development Officer',
        'stage': 'Interview',
        'applicationDate': '2023-09-10',
        'overallScore': 0,
        'referred': False,
        'assessmentAdded': False,
        'email': 'jasmine.wiza@example.com',
        'phone': '+94 75 302 2199',
        'location': 'Moratuwa, Sri Lanka',
        'notes': 'Interview feedback pending from the panel.',
    },
    {
        'id': 'cand-013',
        'name': 'Lola Kirlin',
        'role': 'Research and Development Officer',
        'appliedPosition': 'Research and Development Officer',
        'stage': 'Test',
        'applicationDate': '2023-09-03',
        'overallScore': 4.5,
        'referred': False,
        'assessmentAdded': True,
        'email': 'lola.kirlin@example.com',
        'phone': '+94 77 201 9080',
        'location': 'Battaramulla, Sri Lanka',
        'notes': 'Excellent test result. Candidate looks ready for a final decision.',
    },
    {
        'id': 'cand-014',
        'name': 'Virgil Larkin',
        'role': 'Research and Development Officer',
        'appliedPosition': 'Research and Development Officer',
        'stage': 'Test',
        'applicationDate': '2023-09-03',
        'overallScore': 0,
        'referred': False,
        'assessmentAdded': False,
        'email': 'virgil.larkin@example.com',
        'phone': '+94 72 801 7744',
        'location': 'Dehiwala, Sri Lanka',
        'notes': 'Test assignment has been scheduled but not yet submitted.',
    },
]